-- Database migrations for Nexus (MySQL)
-- Run this file against your MySQL database to create the required tables.

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  fullName VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(64) NOT NULL,
  password VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS packages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  trackingNumber VARCHAR(64) NOT NULL UNIQUE,
  senderName VARCHAR(255) NOT NULL,
  receiverName VARCHAR(255) NOT NULL,
  receiverAddress TEXT NOT NULL,
  receiverPhone VARCHAR(64) NOT NULL,
  packageType VARCHAR(128) NOT NULL,
  weight DECIMAL(10,2) NOT NULL,
  price DECIMAL(12,2) NOT NULL,
  status VARCHAR(64) NOT NULL,
  currentLocation VARCHAR(255) NOT NULL,
  eta DATETIME,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS package_history (
  id INT AUTO_INCREMENT PRIMARY KEY,
  trackingNumber VARCHAR(64) NOT NULL,
  location VARCHAR(255) NOT NULL,
  status VARCHAR(64) NOT NULL,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX(trackingNumber)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  trackingNumber VARCHAR(64) NOT NULL,
  userId INT NOT NULL,
  totalAmount DECIMAL(12,2) NOT NULL,
  invoiceFile VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS chat_messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  message TEXT NOT NULL,
  sender ENUM('user','bot','admin') NOT NULL DEFAULT 'user',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(128) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
